// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceWatch.Modules.Prices.Infrastructure.Persistence;

#nullable disable

namespace PriceWatch.Modules.Prices.Migrations
{
    [DbContext(typeof(PricesDbContext))]
    partial class PricesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceWatch.Modules.Prices.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("ExternalId")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("NbStations")
                        .HasColumnType("int")
                        .HasColumnName("nb_stations");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("short_name");

                    b.HasKey("ExternalId");

                    b.ToTable("prices_brands", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Modules.Prices.Domain.Entities.StationPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("address");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("ExternalStationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_station_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("station_name");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ExternalStationId")
                        .IsUnique();

                    b.ToTable("prices_station_prices", (string)null);
                });

            modelBuilder.Entity("PriceWatch.Modules.Prices.Domain.Entities.StationPrice", b =>
                {
                    b.HasOne("PriceWatch.Modules.Prices.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.OwnsMany("PriceWatch.Modules.Prices.Domain.Entities.FuelPrice", "FuelPrices", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("id"));

                            b1.Property<string>("FuelType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("fuel_type");

                            b1.Property<decimal>("PricePerLiter")
                                .HasColumnType("decimal(8,3)")
                                .HasColumnName("price_per_liter");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("station_price_id")
                                .HasColumnType("char(36)");

                            b1.HasKey("id");

                            b1.HasIndex("station_price_id");

                            b1.ToTable("prices_fuel_prices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("station_price_id");
                        });

                    b.Navigation("Brand");

                    b.Navigation("FuelPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
