// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceWatch.Modules.History.Infrastructure.Persistence;

#nullable disable

namespace PriceWatch.Modules.History.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20260408120423_InitHistory")]
    partial class InitHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceWatch.Modules.History.Domain.Entities.PriceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("ExternalStationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_station_id");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fuel_type");

                    b.Property<decimal>("PricePerLiter")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("price_per_liter");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("station_name");

                    b.HasKey("Id");

                    b.HasIndex("ExternalStationId");

                    b.HasIndex("FuelType");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("ExternalStationId", "FuelType", "RecordedAt");

                    b.ToTable("history_price_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
